---
title: "simpleRegress"
author: "Dominic Garibay"
date: "Fall 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## make a simple regression model

```{r}
bears <- read.csv(file="BEARS.csv",header = TRUE)
#adjust factors to be factors
bears$SEX<- as.factor(bears$SEX)
bears$MONTH<- as.factor(bears$MONTH)
```

## Model LENGTH ~ NECK  this is an example  

```{r}
simp <- lm(LENGTH~NECK,data=bears)
plot(LENGTH~NECK,data=bears)
abline(simp)
summary.lm(simp)
```


## Compare all models that predict LENGTH other than NECK. Then order them from worst to best by its value of Adjusted-Rsquared (bigger is better), or by RSE (residual standard error) where smaller is better. 


```{r}
age <- lm(LENGTH~AGE,data=bears)
plot(LENGTH~AGE,data=bears)
abline(age)
summary.lm(age)
```

```{r}
width <- lm(LENGTH~HEADWTH,data=bears)
plot(LENGTH~HEADWTH,data=bears)
abline(width)
summary.lm(width)
```

```{r}
weight <- lm(LENGTH~WEIGHT,data=bears)
plot(LENGTH~WEIGHT,data=bears)
abline(weight)
summary.lm(weight)
```
